### ISSUE TITLE
Invalid chain-id on InitChain; expected: , got: migaloo-2

### ISSUE THREAD

**Issue by anhductn2001** [White-Whale-Defi-Platform/migaloo-chain#179]
When run interchaintest for start migaloo-chain, I meet a bug:
```go
panic: invalid chain-id on InitChain; expected: , got: migaloo-2
        
        goroutine 11 [running]:
        �github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000da3b00?, {{0x3714bba0, 0xedc128131, 0x0}, {0xc0010001c0, 0x9}, 0xc00062e4e0, {0x5233600, 0x0, 0x0}, ...})
        @       github.com/cosmos/cosmos-sdk@v0.47.2/baseapp/abci.go:39 +0xa54
        �github.com/cometbft/cometbft/abci/client.(*localClient).InitChainSync(0xc0000398c0, {{0x3714bba0, 0xedc128131, 0x0}, {0xc0010001c0, 0x9}, 0xc00062e4e0, {0x5233600, 0x0, 0x0}, ...})
        M       github.com/cometbft/cometbft@v0.37.1/abci/client/local_client.go:275 +0x118
        �github.com/cometbft/cometbft/proxy.(*appConnConsensus).InitChainSync(0xc00034b020, {{0x3714bba0, 0xedc128131, 0x0}, {0xc0010001c0, 0x9}, 0xc00062e4e0, {0x5233600, 0x0, 0x0}, ...})
        B       github.com/cometbft/cometbft@v0.37.1/proxy/app_conn.go:85 +0x137
        �github.com/cometbft/cometbft/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x2e7f89f, 0x6}}, {0xc0010001c0, 0x9}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
        E       github.com/cometbft/cometbft@v0.37.1/consensus/replay.go:319 +0xd78
        hgithub.com/cometbft/cometbft/consensus.(*Handshaker).Handshake(0xc000b61db0, {0x3ab0ae0, 0xc00053a000})
        E       github.com/cometbft/cometbft@v0.37.1/consensus/replay.go:268 +0x3ca
        �github.com/cometbft/cometbft/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x2e7f89f, 0x6}}, {0xc0010001c0, 0x9}, 0x1, 0x0, ...}, ...)
        >       github.com/cometbft/cometbft@v0.37.1/node/node.go:328 +0x198
        �github.com/cometbft/cometbft/node.NewNode(0xc000ce91e0, {0x3a7e660, 0xc000db9f40}, 0xc000d526d0, {0x3a6e840, 0xc0001260a8}, 0x1?, 0x5233600?, 0xc000d528b0, {0x3a97bd8, ...}, ...)
        >       github.com/cometbft/cometbft@v0.37.1/node/node.go:778 +0x56d
        �github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x3aaf2a0, 0xc000ddaa80}, 0x0, {0x0, 0x0}, {0x3ab9ba0, ...}, ...}, ...)
        A       github.com/cosmos/cosmos-sdk@v0.47.2/server/start.go:315 +0x76f
        7github.com/cosmos/cosmos-sdk/server.StartCmd.func2.2()
        @       github.com/cosmos/cosmos-sdk@v0.47.2/server/start.go:151 +0x58
        ;github.com/cosmos/cosmos-sdk/server.wrapCPUProfile.func2()
        @       github.com/cosmos/cosmos-sdk@v0.47.2/server/start.go:551 +0x29
        >created by github.com/cosmos/cosmos-sdk/server.wrapCPUProfile
        A       github.com/cosmos/cosmos-sdk@v0.47.2/server/start.go:550 +0x24a
```

**Comment by anhductn2001** [comment]
@faddat Can you take a look?
